require('dotenv').load()
module.exports = {
    host: 'nhanh.vn',
    port: 443,
    ssl: true,
    prefixPath: null,
    version: process.env.OPEN_NHANH_VERSION || '2.0',
    appId: process.env.OPEN_NHANH_APP_ID || '',
    businessId: process.env.OPEN_NHANH_BUSINESS_ID || '',
    depotId: process.env.OPEN_NHANH_DEPOT_ID || '',
    secretKey: process.env.OPEN_NHANH_APP_SECRET_KEY || '',
    returnURL: process.env.OPEN_NHANH_RETURN_URL || '',
    paths: {
        oauth: 'oauth',
        auth: {
            login: 'login'
        },
        product: {
            add: 'product/item/add?businessId={BUSINESS_ID}',
            edit: 'product/item/add?businessId={BUSINESS_ID}',
            delete: 'product/item/delete?businessId={BUSINESS_ID}',
            search: 'product/item/index?businessId={BUSINESS_ID}',
            uploadImage: 'product/item/uploadimg?businessId={BUSINESS_ID}',
            detail: 'product/item/detail?tab=basic&businessId={BUSINESS_ID}'
        },
        order: {
            search: 'order/manage/index?businessId={BUSINESS_ID}',
            edit: 'order/manage/edit?businessId={BUSINESS_ID}',
            detail: 'order/manage/detail?businessId={BUSINESS_ID}',
            loadOrderData: 'order/manage/loadorderdata?businessId={BUSINESS_ID}',
            delete: 'order/manage/delete?businessId={BUSINESS_ID}',
            changeStatus: 'order/manage/changestatusorder?businessId={BUSINESS_ID}'
        },
        shipping: {
            location: {
                search: 'api/shipping/location?businessId={BUSINESS_ID}'
            },
            handover: {
                add: 'shipping/handover/add?businessId={BUSINESS_ID}'
            }
        }
    },
    business: {
        account: {
            username: process.env.OPEN_NHANH_BUSINESS_USERNAME || '',
            password: process.env.OPEN_NHANH_BUSINESS_PASSWORD || '',
        }
    },
    statuses: [
        {id: 54, name: 'Mới'},
        {id: 57, name: 'Chờ xác nhận'},
        {id: 55, name: 'Đang xác nhận'},
        {id: 56, name: 'Đã xác nhận'},
        {id: 68, name: 'Hết hàng'},
        {id: 73, name: 'Đổi kho hàng'},
        {id: 42, name: 'Đang đóng gói'},
        {id: 40, name: 'Đã đóng gói'},
        {id: 43, name: 'Chờ thu gom'},
        {id: 59, name: 'Đang chuyển'},
        {id: 60, name: 'Thành công'},
        {id: 61, name: 'Thất bại'},
        {id: 63, name: 'Khách hủy'},
        {id: 64, name: 'Hệ thống hủy'},
        {id: 58, name: 'HVC hủy'},
        {id: 71, name: 'Đang hoàn'},
        {id: 74, name: 'Xác nhận hoàn'},
        {id: 72, name: 'Đã hoàn'}
    ],
    reasons: [
        {id: 1, text: 'Đặt nhầm sản phẩm'},
        {id: 2, text: 'Phí vận chuyển cao'},
        {id: 3, text: 'Không muốn chuyển khoản'},
        {id: 4, text: 'Đơn trùng'},
        {id: 5, text: 'Không gọi được khách'},
        {id: 16, text: 'Khách không muốn mua nữa'},
        {id: 11, text: 'Thời gian giao hàng lâu'},
        {id: 12, text: 'Đã mua tại quầy'},
        {id: 18, text: 'Lý do khác'},
    ],
    sources: [
        {id: 1, name: 'Không có nguồn'},
        {id: 2, name: 'Facebook'}
    ],
    data: {
        order: {
            "depot": {"id": 217360, "pickupDepotId": 0},
            "info": {
                "type": 1,
                "mode": 1,
                "saleId": 0,
                "saleName": "",
                "description": "",
                "privateDescription": "Test edit đơn hàng",
                "tagIds": [],
                "technicalStaffId": 0,
                "promotionId": ""
            },
            "customer": {
                "id": 1423,
                "code": "",
                "name": "Duc Nguyen",
                "mobile": "0908119777",
                "email": "",
                "address": "P9, Phường Vĩnh Tuy, Quận Hai Bà Trưng, Hà Nội",
                "birthday": "",
                "facebook": "",
                "gender": "",
                "groupId": 0,
                "cityLocationId": 254,
                "districtLocationId": 322,
                "wardLocationId": 1147,
                "businessName": "",
                "taxCode": "",
                "businessAddress": "",
                "tagIds": []
            },
            "products": [{
                "id": 3498,
                "typeId": 1,
                "code": "25AG69TIMM",
                "name": "25AG69-Áo phông NỮ GUNO trơn dễ phối thời trang 240525 - Tím - M (42-55KG)",
                "apiProductId": "",
                "weight": 500,
                "quantity": 1,
                "price": 119000,
                "discountValue": 0,
                "discount": 0,
                "discountType": "cash",
                "vat": 0,
                "description": "",
                "imeiId": 0,
                "imei": "",
                "priceListId": 0,
                "batchId": 0,
                "combos": [],
                "unitId": 0,
                "gifts": []
            }],
            "carrier": {
                "id": 12,
                "serviceId": 0,
                "serviceCode": "",
                "checkGoods": 4,
                "isFeeCustomerReject": 1,
                "feeCustomerReject": "30000",
                "isPartDelivery": 0,
                "isDeclaredFee": 0,
                "deliveryDate": "",
                "deliveryTime": "",
                "carrierAccountId": 0,
                "carrierShopId": "",
                "declaredValue": null,
                "declaredFee": 0,
                "carrierPromotionCode": "",
                "manualShipFee": "0",
                "customerShipFee": "30000",
                "followTotalFee": 0,
                "orderPackageSize": {"height": 0, "merge": 0, "length": 0, "weight": 0, "width": 0},
                "isSelfConnect": 0,
                "shipFee": 0,
                "codFee": 0,
                "isBrokenGoods": 0,
                "isDropOff": 0
            },
            "payment": {
                "depositAmount": 0,
                "depositAccountId": 0,
                "transferAmount": 0,
                "transferAccountId": 0,
                "installmentAmount": 0,
                "installmentCode": "",
                "installmentAccountId": 0,
                "creditAmount": 0,
                "creditCode": "",
                "creditAccountId": 0,
                "discount": 0,
                "discountType": "cash",
                "vatValue": 0,
                "vatType": "percent",
                "taxCode": "",
                "taxDate": "",
                "debtDueDate": "",
                "cancelAutoPoint": 0,
                "cancelAutoPromotion": 1,
                "totalProductPrice": 0,
                "useManualDiscount": 1
            },
            "channel": {"trafficSourceId": 0}
        },
        product: {
            "info": {
                "name": "Tên sản phảm",
                "code": "Code sản phẩm",
                "barcode": "Barcode sản phẩm",
                "typeId": 1,
                "parentId": "",
                "importPrice": null,
                "price": null,
                "oldPrice": "",
                "wholesalePrice": null,
                "vat": null,
                "status": 1,
                "categoryId": "",
                "internalCategoryId": "",
                "brandId": "",
                "weight": null,
                "length": null,
                "width": null,
                "height": null,
                "unit": "",
                "srcImageAvatar": "",
                "imageUpload": {"name": ""},
                "imageAvatar": "",
                "tagIds": "",
                "copyParentImage": 0,
                "replaceParentName": "",
                "replaceParentCode": ""
            },
            "website": {
                "metaTitle": "",
                "metaDescription": "",
                "metaKeywords": "",
                "otherName": "",
                "video": "",
                "relatedProductIds": [],
                "linkVideos": [],
                "order": "",
                "showHome": 0,
                "showNew": 0,
                "showHot": 0,
                "description": "",
                "content": "",
                "tags": [],
                "promotionValue": "",
                "promotionContent": "",
                "highlights": []
            },
            "branch": {"prices": []},
            "warranty": {"countryId": "", "month": "", "mobile": "", "address": "", "content": ""},
            "remain": {"quantity": null, "depotId": "", "supplierId": ""},
            "combo": {"items": []},
            "attributes": [],
            "multiUnitItems": [{
                "unitName": "",
                "unitQtt": 0,
                "unitPrice": 0,
                "unitImportPrice": 0,
                "unitWholesalePrice": 0
            }],
            "childrens": [],
            "previewSubmit": ""
        }
    }
}
